eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  client:
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://regcentera:6601/eureka/,http://regcenterb:6602/eureka/

hystrix:
  threadpool:
    default:
      coreSize: 500
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 50
        sleepWindowInMilliseconds: 3
      fallback:
        isolation:
          semaphore:
            maxConcurrentReques: 500
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000