server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NewGr8Player/cloud-parent/
          search-paths: config-repo/,config-repo/{application}
          username:
          password: